server:
  servlet:
    context-path: /
  port: 8083

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /api-doc

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/form_db?createDatabaseIfNotExist=true
    username: root
    password: password
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/


  jackson:
    time-zone: Africa/Cairo